[package]
name = "valensas-wiremock-grpc"
version = "0.1.0"
edition = "2021"


[dependencies]
tonic = "0.9.2"
rand = "0.8"
prost = "0.11.9"
tokio = "1"
http-body = "0.4"
log = "0.4"

[build-dependencies]
tonic-build = "0.9.2"
