[package]
name = "wiremock-grpc-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tonic = "0.6.0"
tonic-build = "0.6.0"
prost = "0.9.0"
tokio = "1.12.0"
log = "0.4.14"
http-body = "0.4.4"