[package]
name = "tests_crate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = "1.12.0"
#wiremock-grpc = {path = "../"}
wiremock-grpc = "0.0.2-alpha6"